### ISSUE TITLE
TypeScript Module isn't built correctly

### ISSUE THREAD

**Issue by DmytroFedorov** [targomo/targomo-js-extensions#22]
There is no regular .js file that you want to specify as a module source, you have only .umd.js files. So please fix this mismatch for leaflet and googlemaps as well. Thanks

**Comment by abenrob** [comment]
@silberjan can you weigh in?

**Comment by abenrob** [comment]
@DmytroFedorov can you expand on this?

To install and use, you would do `npm i @targomo/leaflet`, and then `import { foo } from @targomo/leaflet`. What part of this doesn't work?

**Comment by Lionardo** [comment]
I have the same issue but with @targomo/googlemaps

```npm i @targomo/googlemaps```

and 

```import { TgmGoogleMapsPolygonOverlay } from '@targomo/googlemaps'```

result in a error `Cannot find module '@targomo/googlemaps'`

**Comment by toscan** [comment]
Hey, any update here ?

**Comment by Lionardo** [comment]
> I have the same issue but with @targomo/googlemaps
> 
> `npm i @targomo/googlemaps`
> 
> and
> 
> `import { TgmGoogleMapsPolygonOverlay } from '@targomo/googlemaps'`
> 
> result in a error `Cannot find module '@targomo/googlemaps'`

I managed to fix this with dynamic imports. So in my Angular project I couldn't import targomo statically for reasons I don't really know. In the end I just created a async function that would import the module on a event of the user, which is even better.

```js
  private async importTargomoMapsAPI() {
    try {
      const { TgmGoogleMapsPolygonOverlay } = await import('@targomo/googlemaps/targomo-googlemaps-full.umd.js');
      this.layer = new TgmGoogleMapsPolygonOverlay(this.map, {
        strokeWidth: 15
      });
    } catch (error) {
      console.log('error with targomo overlay', error);
    }
  }
```

**Comment by abenrob** [comment]
Thanks for the re-ping on this.
We have a PR (#27) that should set this straight.
Hope to merge this later in the afternoon.

**Comment by abenrob** [comment]
[@targomo/leaflet@0.0.9](https://www.npmjs.com/package/@targomo/leaflet)

[@targomo/googlemaps@0.0.9](https://www.npmjs.com/package/@targomo/googlemaps)

Can you guys see how that works for you? We've fixed definitions for "module" and "typings", and my additional tests are behaving.

**Comment by toscan** [comment]
Thank you for your reactivity. 

We've got another issue here : 
<img width="942" alt="Screenshot 2020-02-20 at 17 21 02" src="https://user-images.githubusercontent.com/3525320/74955783-7011b600-5405-11ea-8aad-109ac5146528.png">

Thanks a lot

**Comment by toscan** [comment]
Solved, thanks !

**Comment by abenrob** [comment]
@toscan when you import the modules, you should be able to import directly from the lib, not the the file i.e.`import { TgmLeafletPolygonOverlay } from '@targomo/leaflet'`

**Comment by abenrob** [comment]
@DmytroFedorov , @Lionardo 
The `main`, `module` and `typings` are now correctly defined in the package.json, so you should be able to correctly import.
