### ISSUE TITLE
Google Maps onRemove void

### ISSUE THREAD

**Issue by abenrob** [targomo/targomo-js-extensions#9]
onRemove is commented out. How does one remove a polygon, and do we need to find a new way to do this other than what is commented out?

https://github.com/targomo/targomo-js-extensions/blob/master/src/google/polygonOverlay.ts#L69

cc: @mtomis

**Comment by abenrob** [comment]
@mtomis is this complete?

**Comment by sephie** [comment]
This was fixed in #10 as far as I know.
